# Generated by Django 5.0.3 on 2024-03-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme')], max_length=5, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('X', 'x'), ('Y', 'Y')], max_length=30, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.CharField(choices=[('X', 'x'), ('Y', 'Y')], max_length=30, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('Ch', 'Chirurgien'), ('O', 'Oncologue')], max_length=30, verbose_name='Specialité'),
        ),
    ]
