# Generated by Django 5.0.3 on 2024-03-06 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médecins'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='histologies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.histology', verbose_name='Histologies'),
        ),
    ]
