# Generated by Django 5.0.3 on 2024-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_doctors_alter_patient_histologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histology',
            name='immunohistochemistry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.immunohistochemistry', verbose_name='Immunohistochimie'),
        ),
    ]
