# Generated by Django 5.0.3 on 2024-03-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_histology_immunohistochemistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='progress',
            field=models.IntegerField(choices=[(0, 'Enregistré'), (25, 'Etat civil'), (50, 'Etude histopathologique'), (75, 'Immunomarquage'), (100, 'Terminé')], default=0, verbose_name='Status'),
        ),
    ]
