# Generated by Django 5.0.3 on 2024-04-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_doctors_patient_primary_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='data',
            field=models.TextField(),
        ),
    ]
