# Generated by Django 5.0.3 on 2024-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0010_alter_patient_histologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
