# Generated by Django 5.0.3 on 2024-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_patient_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="place_of_birth",
            field=models.CharField(
                default="", max_length=150, verbose_name="Lieu de naissance"
            ),
        ),
    ]
