# Generated by Django 5.0.3 on 2024-06-09 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_remove_patient_histologies_remove_prediction_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histology',
            name='immunohistochemistry',
        ),
        migrations.AddField(
            model_name='immunohistochemistry',
            name='histology_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='immunohistochemistry', to='patients.histology'),
            preserve_default=False,
        ),
    ]
