# Generated by Django 5.0.3 on 2024-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_remove_histology_immunohistochemistry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histology',
            options={},
        ),
        migrations.AlterField(
            model_name='histology',
            name='zone',
            field=models.CharField(choices=[('Sein gauche', 'Sein gauche'), ('Sein droit', 'Sein droit'), ('Aisselle gauche', 'Aisselle gauche'), ('Aisselle droit', 'Aisselle droit')], max_length=100, verbose_name='Zone du tissu'),
        ),
        migrations.AlterUniqueTogether(
            name='histology',
            unique_together={('zone', 'patient_id')},
        ),
    ]
